### ISSUE TITLE
support Kotlin 2.2.0

### ISSUE THREAD

**Issue by mohammadd-dev** [realm/realm-kotlin#1870]
https://github.com/XilinJia/krdb

this fork seems good.

**Comment by LouisCAD** [comment]
Wrong link, FYI. Here is the correct one: https://github.com/XilinJia/krdb

**Comment by AndrewBedscastle** [comment]
Doesn't support iOS which renders kmp useless, right?

**Comment by tinoue** [comment]
> Doesn't support iOS

Just because the owner doesn’t have a Mac, using a local build could still be fine.

**Comment by LouisCAD** [comment]
Hello, thanks to https://github.com/XilinJia/krdb, we published a fork on Maven Central yesterday, supporting all targets (iOS and macOS included).

https://github.com/Infomaniak/realm-kotlin/releases/tag/3.2.8-2

**Comment by AndrewBedscastle** [comment]
> Hello, thanks to https://github.com/XilinJia/krdb, we published a fork on Maven Central yesterday, supporting all targets (iOS and macOS included).
> 
> https://github.com/Infomaniak/realm-kotlin/releases/tag/3.2.8-2

Awesome. Will give this a try.
We were about to migrate everything to room. 
Not sure if we still should do it. 
Maybe add new stuff to room, and use this for the existing stuff.

Anyway 
Thanks a lot for your efforts! Highly appreciated

**Comment by josephDevote** [comment]
Still can't believe that MongoDB does not continue to maintain this repo, so disappointing...
