### ISSUE TITLE
Cannot access RealmObject in a multi-module project

### ISSUE THREAD

**Issue by OmarShehe** [realm/realm-kotlin#901]
Projects with multi-module cannot access data class extended with RealmObject. It returns

```
  bad class file: /../lib1/build/intermediates/compile_library_classes_jar/debug/classes.jar(/lib1/RealmObjectExampleModel.class)
undeclared type variable: T
 Please remove or make sure it appears in the correct subdirectory of the classpath.
```

With Java SDK works fine

**Comment by cmelchior** [comment]
Hi @OmarShehe 

Can you explain a bit more about your project setup or provide a sample project demonstrating the issue?

**Comment by OmarShehe** [comment]
Hi @cmelchior 
The issue maybe caused by [android Hilt](https://developer.android.com/training/dependency-injection/hilt-android), but not sure.
It occurred when hilt generated the codes and, at some point, could not identify the class extents `RealmObject`.
I create an example project; here is the [link](https://github.com/OmarShehe/RealmProject)

This [codes](https://github.com/OmarShehe/RealmProject/blob/769ea81d234484406863cf4239ce36929ffc310b/app/src/main/java/com/example/realmproject/MainActivity.kt#L18-L19) are the ones cause the issue

**Comment by OmarShehe** [comment]
> Hello @OmarShehe
> 
> Did you find any work around ?
> 
> I'm migrating to Realm Kotlin SDK, using Hilt and I encounter the same error message for my models... Kinda stuck on this one and thinking to just do the migration later.

Hello @Neoxsam, There is a workaround, but I'm not sure if you will like the approach.
**The problem is that:** The compiler does not recognize the `realmObject` outside the `module`.

What you need to do is to have two data models. Linke `FrogDto` and `FrogModel`
`FrogDto` inherited the `realmObject`; only uses it inside the module, and `FrogModel` is just a plain data model; you can use it outside the module.

**Comment by Neoxsam** [comment]
Thanks for your workaround and investigation guys. 
I will check that and be  be sure to follow the issue

**Comment by cmelchior** [comment]
We have merged a fix which works in the project here: https://github.com/realm/realm-kotlin/issues/901#issuecomment-1160393534

It should be available in a 1.0.1-SNAPSHOT release within a couple of hours.

**Comment by cmelchior** [comment]
A `1.0.1-SNAPSHOT` should be available now. You can see here https://github.com/realm/realm-kotlin#using-snapshots how to use it.

**Comment by OmarShehe** [comment]
@cmelchior Did you have time to test it out? Because I'm still receiving the same error. You can run the same [project](https://github.com/OmarShehe/RealmProject); now, it uses the snapshots `1.0.1-SNAPSHOT`

**Comment by OmarShehe** [comment]
@cmelchior, I confirm that `1.0.1-SNAPSHOT` is working just fine 💯; You can ignore my other message; I forgot to change the plugin version.

Thank you again for the quick fix; I appreciate it 🙏
